### ISSUE TITLE
Developer setup deploys TripleO Wallaby CentOS 8 containers on CentOS 9 host

### ISSUE THREAD

**Issue by jistr** [openstack-k8s-operators/data-plane-adoption#94]
Here is generated containers-prepare-parameters.yaml:

```
parameter_defaults:
  ContainerImagePrepare:
  - set:
      ceph_alertmanager_image: alertmanager
      ceph_alertmanager_namespace: quay.io/prometheus
      ceph_alertmanager_tag: v0.20.0
      ceph_grafana_image: ceph-grafana
      ceph_grafana_namespace: quay.io/ceph
      ceph_grafana_tag: 6.7.4
      ceph_image: daemon
      ceph_namespace: quay.rdoproject.org/tripleowallabycentos9
      ceph_node_exporter_image: node-exporter
      ceph_node_exporter_namespace: quay.io/prometheus
      ceph_node_exporter_tag: v0.18.1
      ceph_prometheus_image: prometheus
      ceph_prometheus_namespace: quay.io/prometheus
      ceph_prometheus_tag: v2.18.1
      ceph_tag: current-ceph
      name_prefix: openstack-
      name_suffix: ''
      namespace: quay.io/tripleowallaby
      neutron_driver: ovn
      rhel_containers: false
      tag: current-tripleo
    tag_from_label: rdo_version

```
